import { db } from '@/db';
import { emailContacts, emailLists } from '@/db/schema';
import { eq } from 'drizzle-orm';

async function main() {
    const now = new Date();
    
    // Helper function to get date N days ago
    const daysAgo = (days: number) => {
        const date = new Date(now);
        date.setDate(date.getDate() - days);
        return date.toISOString();
    };

    // List 1: Tech Startups Q1 - 15 contacts (25-20 days ago)
    const techStartups = [
        {
            listId: 1,
            email: 'sarah.chen@nexusai.com',
            firstName: 'Sarah',
            lastName: 'Chen',
            company: 'Nexus AI',
            position: 'CEO & Founder',
            customFields: JSON.stringify({ industry: 'technology', companySize: '10-50', fundingStage: 'seed' }),
            isActive: true,
            createdAt: daysAgo(25),
            updatedAt: daysAgo(25),
        },
        {
            listId: 1,
            email: 'michael.rodriguez@cloudshift.io',
            firstName: 'Michael',
            lastName: 'Rodriguez',
            company: 'CloudShift',
            position: 'CTO',
            customFields: JSON.stringify({ industry: 'technology', companySize: '20-50', fundingStage: 'seriesA' }),
            isActive: true,
            createdAt: daysAgo(24),
            updatedAt: daysAgo(24),
        },
        {
            listId: 1,
            email: 'emily.watson@datastream.tech',
            firstName: 'Emily',
            lastName: 'Watson',
            company: 'DataStream Tech',
            position: 'Co-Founder',
            customFields: JSON.stringify({ industry: 'technology', companySize: '15-50', fundingStage: 'seed' }),
            isActive: true,
            createdAt: daysAgo(24),
            updatedAt: daysAgo(24),
        },
        {
            listId: 1,
            email: 'david@techhaven.io',
            firstName: 'David',
            lastName: 'Kim',
            company: 'TechHaven',
            position: 'Founder',
            customFields: JSON.stringify({ industry: 'technology', companySize: '10-30', fundingStage: 'seed' }),
            isActive: true,
            createdAt: daysAgo(23),
            updatedAt: daysAgo(23),
        },
        {
            listId: 1,
            email: 'jessica.martinez@quantumleap.ai',
            firstName: 'Jessica',
            lastName: 'Martinez',
            company: 'QuantumLeap AI',
            position: 'CEO',
            customFields: JSON.stringify({ industry: 'technology', companySize: '25-50', fundingStage: 'seriesA' }),
            isActive: true,
            createdAt: daysAgo(23),
            updatedAt: daysAgo(23),
        },
        {
            listId: 1,
            email: 'alex.thompson@innovatex.com',
            firstName: 'Alex',
            lastName: 'Thompson',
            company: 'InnovateX',
            position: 'CTO & Co-Founder',
            customFields: JSON.stringify({ industry: 'technology', companySize: '30-50', fundingStage: 'seriesA' }),
            isActive: true,
            createdAt: daysAgo(22),
            updatedAt: daysAgo(22),
        },
        {
            listId: 1,
            email: 'rachel.patel@pixelforge.tech',
            firstName: 'Rachel',
            lastName: 'Patel',
            company: 'PixelForge',
            position: 'Founder',
            customFields: JSON.stringify({ industry: 'technology', companySize: '12-30', fundingStage: 'seed' }),
            isActive: true,
            createdAt: daysAgo(22),
            updatedAt: daysAgo(22),
        },
        {
            listId: 1,
            email: 'james.lee@codewave.io',
            firstName: 'James',
            lastName: 'Lee',
            company: 'CodeWave',
            position: 'CEO',
            customFields: JSON.stringify({ industry: 'technology', companySize: '18-40', fundingStage: 'seed' }),
            isActive: true,
            createdAt: daysAgo(21),
            updatedAt: daysAgo(21),
        },
        {
            listId: 1,
            email: 'sophia.anderson@blockforge.tech',
            firstName: 'Sophia',
            lastName: 'Anderson',
            company: 'BlockForge',
            position: 'Co-Founder & CTO',
            customFields: JSON.stringify({ industry: 'technology', companySize: '15-35', fundingStage: 'seed' }),
            isActive: true,
            createdAt: daysAgo(21),
            updatedAt: daysAgo(21),
        },
        {
            listId: 1,
            email: 'daniel@velocitytech.com',
            firstName: 'Daniel',
            lastName: 'Brown',
            company: 'Velocity Tech',
            position: 'Founder',
            customFields: JSON.stringify({ industry: 'technology', companySize: '22-45', fundingStage: 'seriesA' }),
            isActive: true,
            createdAt: daysAgo(20),
            updatedAt: daysAgo(20),
        },
        {
            listId: 1,
            email: 'olivia.nguyen@synthwave.ai',
            firstName: 'Olivia',
            lastName: 'Nguyen',
            company: 'SynthWave AI',
            position: 'CEO & Founder',
            customFields: JSON.stringify({ industry: 'technology', companySize: '28-50', fundingStage: 'seriesA' }),
            isActive: true,
            createdAt: daysAgo(20),
            updatedAt: daysAgo(20),
        },
        {
            listId: 1,
            email: 'marcus.wilson@edgecompute.io',
            firstName: 'Marcus',
            lastName: 'Wilson',
            company: 'EdgeCompute',
            position: 'CTO',
            customFields: JSON.stringify({ industry: 'technology', companySize: '20-40', fundingStage: 'seed' }),
            isActive: true,
            createdAt: daysAgo(20),
            updatedAt: daysAgo(20),
        },
        {
            listId: 1,
            email: 'amanda.davis@fusionlab.tech',
            firstName: 'Amanda',
            lastName: 'Davis',
            company: 'FusionLab',
            position: 'Co-Founder',
            customFields: JSON.stringify({ industry: 'technology', companySize: '16-35', fundingStage: 'seed' }),
            isActive: true,
            createdAt: daysAgo(20),
            updatedAt: daysAgo(20),
        },
        {
            listId: 1,
            email: 'kevin.zhang@nanotech.io',
            firstName: 'Kevin',
            lastName: 'Zhang',
            company: 'NanoTech Systems',
            position: 'Founder & CEO',
            customFields: JSON.stringify({ industry: 'technology', companySize: '24-48', fundingStage: 'seriesA' }),
            isActive: true,
            createdAt: daysAgo(20),
            updatedAt: daysAgo(20),
        },
        {
            listId: 1,
            email: 'laura.mitchell@hyperloop.tech',
            firstName: 'Laura',
            lastName: 'Mitchell',
            company: 'Hyperloop Tech',
            position: 'CTO & Co-Founder',
            customFields: JSON.stringify({ industry: 'technology', companySize: '32-50', fundingStage: 'seriesA' }),
            isActive: true,
            createdAt: daysAgo(20),
            updatedAt: daysAgo(20),
        },
    ];

    // List 2: Marketing Leads - 20 contacts (20-15 days ago)
    const marketingLeads = [
        {
            listId: 2,
            email: 'jennifer.clark@acmecorp.com',
            firstName: 'Jennifer',
            lastName: 'Clark',
            company: 'Acme Corporation',
            position: 'CMO',
            customFields: JSON.stringify({ department: 'marketing', companySize: '200-500', marketingBudget: '150k-200k' }),
            isActive: true,
            createdAt: daysAgo(20),
            updatedAt: daysAgo(20),
        },
        {
            listId: 2,
            email: 'robert.taylor@globalreach.com',
            firstName: 'Robert',
            lastName: 'Taylor',
            company: 'Global Reach Media',
            position: 'Marketing Director',
            customFields: JSON.stringify({ department: 'marketing', companySize: '100-300', marketingBudget: '80k-150k' }),
            isActive: true,
            createdAt: daysAgo(19),
            updatedAt: daysAgo(19),
        },
        {
            listId: 2,
            email: 'maria.garcia@techsolutions.com',
            firstName: 'Maria',
            lastName: 'Garcia',
            company: 'TechSolutions Inc',
            position: 'Head of Marketing',
            customFields: JSON.stringify({ department: 'marketing', companySize: '150-400', marketingBudget: '100k-180k' }),
            isActive: true,
            createdAt: daysAgo(19),
            updatedAt: daysAgo(19),
        },
        {
            listId: 2,
            email: 'william.jones@innovatebrand.com',
            firstName: 'William',
            lastName: 'Jones',
            company: 'Innovate Brand',
            position: 'VP Marketing',
            customFields: JSON.stringify({ department: 'marketing', companySize: '250-500', marketingBudget: '150k-200k' }),
            isActive: true,
            createdAt: daysAgo(18),
            updatedAt: daysAgo(18),
        },
        {
            listId: 2,
            email: 'lisa.white@digitalwave.com',
            firstName: 'Lisa',
            lastName: 'White',
            company: 'DigitalWave',
            position: 'Marketing Director',
            customFields: JSON.stringify({ department: 'marketing', companySize: '80-200', marketingBudget: '60k-120k' }),
            isActive: true,
            createdAt: daysAgo(18),
            updatedAt: daysAgo(18),
        },
        {
            listId: 2,
            email: 'thomas.martin@growthco.com',
            firstName: 'Thomas',
            lastName: 'Martin',
            company: 'GrowthCo',
            position: 'CMO',
            customFields: JSON.stringify({ department: 'marketing', companySize: '180-450', marketingBudget: '120k-190k' }),
            isActive: true,
            createdAt: daysAgo(18),
            updatedAt: daysAgo(18),
        },
        {
            listId: 2,
            email: 'patricia.moore@brandbuilders.com',
            firstName: 'Patricia',
            lastName: 'Moore',
            company: 'Brand Builders',
            position: 'Head of Marketing',
            customFields: JSON.stringify({ department: 'marketing', companySize: '120-350', marketingBudget: '90k-160k' }),
            isActive: true,
            createdAt: daysAgo(17),
            updatedAt: daysAgo(17),
        },
        {
            listId: 2,
            email: 'christopher.hall@marketpro.com',
            firstName: 'Christopher',
            lastName: 'Hall',
            company: 'MarketPro',
            position: 'VP Marketing',
            customFields: JSON.stringify({ department: 'marketing', companySize: '200-480', marketingBudget: '140k-200k' }),
            isActive: true,
            createdAt: daysAgo(17),
            updatedAt: daysAgo(17),
        },
        {
            listId: 2,
            email: 'nancy.lewis@audiencemax.com',
            firstName: 'Nancy',
            lastName: 'Lewis',
            company: 'AudienceMax',
            position: 'Marketing Director',
            customFields: JSON.stringify({ department: 'marketing', companySize: '90-250', marketingBudget: '70k-140k' }),
            isActive: true,
            createdAt: daysAgo(17),
            updatedAt: daysAgo(17),
        },
        {
            listId: 2,
            email: 'steven.walker@engagementpro.com',
            firstName: 'Steven',
            lastName: 'Walker',
            company: 'EngagementPro',
            position: 'CMO',
            customFields: JSON.stringify({ department: 'marketing', companySize: '160-400', marketingBudget: '110k-180k' }),
            isActive: true,
            createdAt: daysAgo(16),
            updatedAt: daysAgo(16),
        },
        {
            listId: 2,
            email: 'karen.young@leadgenco.com',
            firstName: 'Karen',
            lastName: 'Young',
            company: 'LeadGen Co',
            position: 'Head of Marketing',
            customFields: JSON.stringify({ department: 'marketing', companySize: '110-300', marketingBudget: '85k-155k' }),
            isActive: true,
            createdAt: daysAgo(16),
            updatedAt: daysAgo(16),
        },
        {
            listId: 2,
            email: 'brian.allen@contentking.com',
            firstName: 'Brian',
            lastName: 'Allen',
            company: 'Content King',
            position: 'VP Marketing',
            customFields: JSON.stringify({ department: 'marketing', companySize: '140-380', marketingBudget: '100k-175k' }),
            isActive: true,
            createdAt: daysAgo(16),
            updatedAt: daysAgo(16),
        },
        {
            listId: 2,
            email: 'michelle.king@socialbuzz.com',
            firstName: 'Michelle',
            lastName: 'King',
            company: 'SocialBuzz',
            position: 'Marketing Director',
            customFields: JSON.stringify({ department: 'marketing', companySize: '75-220', marketingBudget: '55k-130k' }),
            isActive: true,
            createdAt: daysAgo(15),
            updatedAt: daysAgo(15),
        },
        {
            listId: 2,
            email: 'george.wright@demandgen.com',
            firstName: 'George',
            lastName: 'Wright',
            company: 'DemandGen Solutions',
            position: 'CMO',
            customFields: JSON.stringify({ department: 'marketing', companySize: '190-450', marketingBudget: '130k-195k' }),
            isActive: true,
            createdAt: daysAgo(15),
            updatedAt: daysAgo(15),
        },
        {
            listId: 2,
            email: 'betty.lopez@growthmarketing.com',
            firstName: 'Betty',
            lastName: 'Lopez',
            company: 'Growth Marketing Hub',
            position: 'Head of Marketing',
            customFields: JSON.stringify({ department: 'marketing', companySize: '130-360', marketingBudget: '95k-165k' }),
            isActive: true,
            createdAt: daysAgo(15),
            updatedAt: daysAgo(15),
        },
        {
            listId: 2,
            email: 'edward.hill@conversionlab.com',
            firstName: 'Edward',
            lastName: 'Hill',
            company: 'Conversion Lab',
            position: 'VP Marketing',
            customFields: JSON.stringify({ department: 'marketing', companySize: '170-420', marketingBudget: '115k-185k' }),
            isActive: true,
            createdAt: daysAgo(15),
            updatedAt: daysAgo(15),
        },
        {
            listId: 2,
            email: 'sandra.scott@brandevolution.com',
            firstName: 'Sandra',
            lastName: 'Scott',
            company: 'Brand Evolution',
            position: 'Marketing Director',
            customFields: JSON.stringify({ department: 'marketing', companySize: '95-280', marketingBudget: '75k-145k' }),
            isActive: true,
            createdAt: daysAgo(15),
            updatedAt: daysAgo(15),
        },
        {
            listId: 2,
            email: 'donald.green@customerreach.com',
            firstName: 'Donald',
            lastName: 'Green',
            company: 'Customer Reach',
            position: 'CMO',
            customFields: JSON.stringify({ department: 'marketing', companySize: '210-490', marketingBudget: '145k-200k' }),
            isActive: true,
            createdAt: daysAgo(15),
            updatedAt: daysAgo(15),
        },
        {
            listId: 2,
            email: 'ashley.adams@audiencefirst.com',
            firstName: 'Ashley',
            lastName: 'Adams',
            company: 'Audience First',
            position: 'Head of Marketing',
            customFields: JSON.stringify({ department: 'marketing', companySize: '105-320', marketingBudget: '80k-150k' }),
            isActive: true,
            createdAt: daysAgo(15),
            updatedAt: daysAgo(15),
        },
        {
            listId: 2,
            email: 'kenneth.baker@marketingmastery.com',
            firstName: 'Kenneth',
            lastName: 'Baker',
            company: 'Marketing Mastery',
            position: 'VP Marketing',
            customFields: JSON.stringify({ department: 'marketing', companySize: '155-410', marketingBudget: '105k-170k' }),
            isActive: true,
            createdAt: daysAgo(15),
            updatedAt: daysAgo(15),
        },
    ];

    // List 3: Enterprise Prospects - 12 contacts (18-12 days ago)
    const enterpriseProspects = [
        {
            listId: 3,
            email: 'john.peterson@globaltech.com',
            firstName: 'John',
            lastName: 'Peterson',
            company: 'GlobalTech Industries',
            position: 'CTO',
            customFields: JSON.stringify({ industry: 'enterprise', companySize: '1000+', decisionMaker: true }),
            isActive: true,
            createdAt: daysAgo(18),
            updatedAt: daysAgo(18),
        },
        {
            listId: 3,
            email: 'elizabeth.cooper@megacorp.com',
            firstName: 'Elizabeth',
            lastName: 'Cooper',
            company: 'MegaCorp Solutions',
            position: 'VP Engineering',
            customFields: JSON.stringify({ industry: 'enterprise', companySize: '1000+', decisionMaker: true }),
            isActive: true,
            createdAt: daysAgo(17),
            updatedAt: daysAgo(17),
        },
        {
            listId: 3,
            email: 'richard.reed@enterprisesys.com',
            firstName: 'Richard',
            lastName: 'Reed',
            company: 'Enterprise Systems Corp',
            position: 'Director of IT',
            customFields: JSON.stringify({ industry: 'enterprise', companySize: '1000+', decisionMaker: true }),
            isActive: true,
            createdAt: daysAgo(17),
            updatedAt: daysAgo(17),
        },
        {
            listId: 3,
            email: 'barbara.morgan@techholdingsltd.com',
            firstName: 'Barbara',
            lastName: 'Morgan',
            company: 'Tech Holdings Ltd',
            position: 'Enterprise Architect',
            customFields: JSON.stringify({ industry: 'enterprise', companySize: '1000+', decisionMaker: true }),
            isActive: true,
            createdAt: daysAgo(16),
            updatedAt: daysAgo(16),
        },
        {
            listId: 3,
            email: 'joseph.bell@universaltech.com',
            firstName: 'Joseph',
            lastName: 'Bell',
            company: 'Universal Tech Group',
            position: 'CTO',
            customFields: JSON.stringify({ industry: 'enterprise', companySize: '1000+', decisionMaker: true }),
            isActive: true,
            createdAt: daysAgo(16),
            updatedAt: daysAgo(16),
        },
        {
            listId: 3,
            email: 'susan.murphy@infinitecorp.com',
            firstName: 'Susan',
            lastName: 'Murphy',
            company: 'Infinite Corporation',
            position: 'VP Engineering',
            customFields: JSON.stringify({ industry: 'enterprise', companySize: '1000+', decisionMaker: true }),
            isActive: true,
            createdAt: daysAgo(15),
            updatedAt: daysAgo(15),
        },
        {
            listId: 3,
            email: 'charles.rivera@primeindustries.com',
            firstName: 'Charles',
            lastName: 'Rivera',
            company: 'Prime Industries',
            position: 'Director of IT',
            customFields: JSON.stringify({ industry: 'enterprise', companySize: '1000+', decisionMaker: true }),
            isActive: true,
            createdAt: daysAgo(15),
            updatedAt: daysAgo(15),
        },
        {
            listId: 3,
            email: 'margaret.cook@apexsystems.com',
            firstName: 'Margaret',
            lastName: 'Cook',
            company: 'Apex Systems Inc',
            position: 'Enterprise Architect',
            customFields: JSON.stringify({ industry: 'enterprise', companySize: '1000+', decisionMaker: true }),
            isActive: true,
            createdAt: daysAgo(14),
            updatedAt: daysAgo(14),
        },
        {
            listId: 3,
            email: 'paul.bailey@synergycorp.com',
            firstName: 'Paul',
            lastName: 'Bailey',
            company: 'Synergy Corporation',
            position: 'CTO',
            customFields: JSON.stringify({ industry: 'enterprise', companySize: '1000+', decisionMaker: true }),
            isActive: true,
            createdAt: daysAgo(14),
            updatedAt: daysAgo(14),
        },
        {
            listId: 3,
            email: 'dorothy.howard@globalenterprise.com',
            firstName: 'Dorothy',
            lastName: 'Howard',
            company: 'Global Enterprise Ltd',
            position: 'VP Engineering',
            customFields: JSON.stringify({ industry: 'enterprise', companySize: '1000+', decisionMaker: true }),
            isActive: true,
            createdAt: daysAgo(13),
            updatedAt: daysAgo(13),
        },
        {
            listId: 3,
            email: 'mark.ward@techgiantsinc.com',
            firstName: 'Mark',
            lastName: 'Ward',
            company: 'Tech Giants Inc',
            position: 'Director of IT',
            customFields: JSON.stringify({ industry: 'enterprise', companySize: '1000+', decisionMaker: true }),
            isActive: true,
            createdAt: daysAgo(13),
            updatedAt: daysAgo(13),
        },
        {
            listId: 3,
            email: 'helen.torres@ultimatesolutions.com',
            firstName: 'Helen',
            lastName: 'Torres',
            company: 'Ultimate Solutions Corp',
            position: 'Enterprise Architect',
            customFields: JSON.stringify({ industry: 'enterprise', companySize: '1000+', decisionMaker: true }),
            isActive: true,
            createdAt: daysAgo(12),
            updatedAt: daysAgo(12),
        },
    ];

    // List 4: SaaS Founders - 10 contacts (15-10 days ago)
    const saasFounders = [
        {
            listId: 4,
            email: 'ryan.collins@projecthub.io',
            firstName: 'Ryan',
            lastName: 'Collins',
            company: 'ProjectHub',
            position: 'CEO & Founder',
            customFields: JSON.stringify({ businessModel: 'B2B SaaS', revenue: '500k-1M', employees: '20-50' }),
            isActive: true,
            createdAt: daysAgo(15),
            updatedAt: daysAgo(15),
        },
        {
            listId: 4,
            email: 'christina.stewart@workflowpro.com',
            firstName: 'Christina',
            lastName: 'Stewart',
            company: 'WorkflowPro',
            position: 'Founder',
            customFields: JSON.stringify({ businessModel: 'B2B SaaS', revenue: '300k-800k', employees: '15-40' }),
            isActive: true,
            createdAt: daysAgo(14),
            updatedAt: daysAgo(14),
        },
        {
            listId: 4,
            email: 'jason.sanchez@teamcollab.io',
            firstName: 'Jason',
            lastName: 'Sanchez',
            company: 'TeamCollab',
            position: 'Co-Founder',
            customFields: JSON.stringify({ businessModel: 'B2B SaaS', revenue: '200k-600k', employees: '10-35' }),
            isActive: true,
            createdAt: daysAgo(14),
            updatedAt: daysAgo(14),
        },
        {
            listId: 4,
            email: 'angela.morris@cloudsync.io',
            firstName: 'Angela',
            lastName: 'Morris',
            company: 'CloudSync',
            position: 'CEO',
            customFields: JSON.stringify({ businessModel: 'B2B SaaS', revenue: '400k-1M', employees: '25-50' }),
            isActive: true,
            createdAt: daysAgo(13),
            updatedAt: daysAgo(13),
        },
        {
            listId: 4,
            email: 'jeffrey.rogers@datapipeline.io',
            firstName: 'Jeffrey',
            lastName: 'Rogers',
            company: 'DataPipeline',
            position: 'Founder',
            customFields: JSON.stringify({ businessModel: 'B2B SaaS', revenue: '350k-900k', employees: '18-45' }),
            isActive: true,
            createdAt: daysAgo(13),
            updatedAt: daysAgo(13),
        },
        {
            listId: 4,
            email: 'melissa.reed@analyticsplus.io',
            firstName: 'Melissa',
            lastName: 'Reed',
            company: 'AnalyticsPlus',
            position: 'Co-Founder',
            customFields: JSON.stringify({ businessModel: 'B2B SaaS', revenue: '250k-700k', employees: '12-38' }),
            isActive: true,
            createdAt: daysAgo(12),
            updatedAt: daysAgo(12),
        },
        {
            listId: 4,
            email: 'gregory.cook@apihub.io',
            firstName: 'Gregory',
            lastName: 'Cook',
            company: 'ApiHub',
            position: 'CEO & Founder',
            customFields: JSON.stringify({ businessModel: 'B2B SaaS', revenue: '450k-1M', employees: '22-48' }),
            isActive: true,
            createdAt: daysAgo(12),
            updatedAt: daysAgo(12),
        },
        {
            listId: 4,
            email: 'deborah.bailey@automateflow.io',
            firstName: 'Deborah',
            lastName: 'Bailey',
            company: 'AutomateFlow',
            position: 'Founder',
            customFields: JSON.stringify({ businessModel: 'B2B SaaS', revenue: '180k-550k', employees: '8-32' }),
            isActive: true,
            createdAt: daysAgo(11),
            updatedAt: daysAgo(11),
        },
        {
            listId: 4,
            email: 'kevin.howard@invoicemaster.io',
            firstName: 'Kevin',
            lastName: 'Howard',
            company: 'InvoiceMaster',
            position: 'Co-Founder',
            customFields: JSON.stringify({ businessModel: 'B2B SaaS', revenue: '320k-850k', employees: '16-42' }),
            isActive: true,
            createdAt: daysAgo(11),
            updatedAt: daysAgo(11),
        },
        {
            listId: 4,
            email: 'stephanie.ward@customersync.io',
            firstName: 'Stephanie',
            lastName: 'Ward',
            company: 'CustomerSync',
            position: 'CEO',
            customFields: JSON.stringify({ businessModel: 'B2B SaaS', revenue: '280k-750k', employees: '14-40' }),
            isActive: true,
            createdAt: daysAgo(10),
            updatedAt: daysAgo(10),
        },
    ];

    // List 5: Product Managers - 13 contacts (10-5 days ago)
    const productManagers = [
        {
            listId: 5,
            email: 'andrew.cox@techventures.com',
            firstName: 'Andrew',
            lastName: 'Cox',
            company: 'TechVentures',
            position: 'Product Manager',
            customFields: JSON.stringify({ role: 'product', experience: '5-7 years', productType: 'B2B' }),
            isActive: true,
            createdAt: daysAgo(10),
            updatedAt: daysAgo(10),
        },
        {
            listId: 5,
            email: 'kathleen.richardson@innovatesolutions.com',
            firstName: 'Kathleen',
            lastName: 'Richardson',
            company: 'Innovate Solutions',
            position: 'Senior PM',
            customFields: JSON.stringify({ role: 'product', experience: '7-10 years', productType: 'B2B' }),
            isActive: true,
            createdAt: daysAgo(9),
            updatedAt: daysAgo(9),
        },
        {
            listId: 5,
            email: 'justin.wood@productfirst.com',
            firstName: 'Justin',
            lastName: 'Wood',
            company: 'ProductFirst',
            position: 'Head of Product',
            customFields: JSON.stringify({ role: 'product', experience: '8-10 years', productType: 'B2C' }),
            isActive: true,
            createdAt: daysAgo(9),
            updatedAt: daysAgo(9),
        },
        {
            listId: 5,
            email: 'carolyn.watson@digitalpro.com',
            firstName: 'Carolyn',
            lastName: 'Watson',
            company: 'DigitalPro',
            position: 'VP Product',
            customFields: JSON.stringify({ role: 'product', experience: '9-10 years', productType: 'B2B' }),
            isActive: true,
            createdAt: daysAgo(8),
            updatedAt: daysAgo(8),
        },
        {
            listId: 5,
            email: 'adam.brooks@cloudproducts.com',
            firstName: 'Adam',
            lastName: 'Brooks',
            company: 'CloudProducts Inc',
            position: 'Product Manager',
            customFields: JSON.stringify({ role: 'product', experience: '5-8 years', productType: 'B2B' }),
            isActive: true,
            createdAt: daysAgo(8),
            updatedAt: daysAgo(8),
        },
        {
            listId: 5,
            email: 'sharon.kelly@techflow.com',
            firstName: 'Sharon',
            lastName: 'Kelly',
            company: 'TechFlow',
            position: 'Senior PM',
            customFields: JSON.stringify({ role: 'product', experience: '6-9 years', productType: 'B2C' }),
            isActive: true,
            createdAt: daysAgo(7),
            updatedAt: daysAgo(7),
        },
        {
            listId: 5,
            email: 'benjamin.sanders@platformx.com',
            firstName: 'Benjamin',
            lastName: 'Sanders',
            company: 'PlatformX',
            position: 'Head of Product',
            customFields: JSON.stringify({ role: 'product', experience: '8-10 years', productType: 'B2B' }),
            isActive: true,
            createdAt: daysAgo(7),
            updatedAt: daysAgo(7),
        },
        {
            listId: 5,
            email: 'cynthia.price@growthproducts.com',
            firstName: 'Cynthia',
            lastName: 'Price',
            company: 'Growth Products',
            position: 'VP Product',
            customFields: JSON.stringify({ role: 'product', experience: '9-10 years', productType: 'B2B' }),
            isActive: true,
            createdAt: daysAgo(6),
            updatedAt: daysAgo(6),
        },
        {
            listId: 5,
            email: 'frank.bennett@agilepro.com',
            firstName: 'Frank',
            lastName: 'Bennett',
            company: 'AgilePro',
            position: 'Product Manager',
            customFields: JSON.stringify({ role: 'product', experience: '5-7 years', productType: 'B2C' }),
            isActive: true,
            createdAt: daysAgo(6),
            updatedAt: daysAgo(6),
        },
        {
            listId: 5,
            email: 'pamela.wood@userfirst.com',
            firstName: 'Pamela',
            lastName: 'Wood',
            company: 'UserFirst',
            position: 'Senior PM',
            customFields: JSON.stringify({ role: 'product', experience: '6-9 years', productType: 'B2B' }),
            isActive: true,
            createdAt: daysAgo(6),
            updatedAt: daysAgo(6),
        },
        {
            listId: 5,
            email: 'ralph.barnes@featureflow.com',
            firstName: 'Ralph',
            lastName: 'Barnes',
            company: 'FeatureFlow',
            position: 'Head of Product',
            customFields: JSON.stringify({ role: 'product', experience: '7-10 years', productType: 'B2B' }),
            isActive: true,
            createdAt: daysAgo(5),
            updatedAt: daysAgo(5),
        },
        {
            listId: 5,
            email: 'evelyn.ross@productlabs.com',
            firstName: 'Evelyn',
            lastName: 'Ross',
            company: 'Product Labs',
            position: 'VP Product',
            customFields: JSON.stringify({ role: 'product', experience: '8-10 years', productType: 'B2C' }),
            isActive: true,
            createdAt: daysAgo(5),
            updatedAt: daysAgo(5),
        },
        {
            listId: 5,
            email: 'harold.henderson@visionproducts.com',
            firstName: 'Harold',
            lastName: 'Henderson',
            company: 'Vision Products',
            position: 'Product Manager',
            customFields: JSON.stringify({ role: 'product', experience: '5-8 years', productType: 'B2B' }),
            isActive: true,
            createdAt: daysAgo(5),
            updatedAt: daysAgo(5),
        },
    ];

    // Combine all contacts
    const allContacts = [
        ...techStartups,
        ...marketingLeads,
        ...enterpriseProspects,
        ...saasFounders,
        ...productManagers,
    ];

    // Insert all contacts
    await db.insert(emailContacts).values(allContacts);

    // Update totalContacts for each list
    await db.update(emailLists).set({ totalContacts: 15 }).where(eq(emailLists.id, 1));
    await db.update(emailLists).set({ totalContacts: 20 }).where(eq(emailLists.id, 2));
    await db.update(emailLists).set({ totalContacts: 12 }).where(eq(emailLists.id, 3));
    await db.update(emailLists).set({ totalContacts: 10 }).where(eq(emailLists.id, 4));
    await db.update(emailLists).set({ totalContacts: 13 }).where(eq(emailLists.id, 5));

    console.log('✅ Email contacts seeder completed successfully');
    console.log('📊 Total contacts seeded: 70');
    console.log('📋 List 1 (Tech Startups Q1): 15 contacts');
    console.log('📋 List 2 (Marketing Leads): 20 contacts');
    console.log('📋 List 3 (Enterprise Prospects): 12 contacts');
    console.log('📋 List 4 (SaaS Founders): 10 contacts');
    console.log('📋 List 5 (Product Managers): 13 contacts');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});